# __version__.py
# autogenerated by keats 0.2.28
__version__ = "0.1.0"
__name__ = "caldera"
__title__ = "caldera"
__authors__ = ["Justin Vrana <justin.vrana@gmail.com>"]
__repo__ = None
__homepage__ = "http://www.github.com/jvrana/caldera"
__description__ = ""
