# @package _group_
model: Network
encode:
    node:
        size: ${network.size}
        depth: ${network.depth}
        layer_norm: ${network.layer_norm}
        activation: ${network.activation}
        dropout: ${network.dropout}
    edge:
        size: ${network.size}
        depth: ${network.depth}
        layer_norm: ${network.layer_norm}
        activation: ${network.activation}
        dropout: ${network.dropout}
    glob:
        size: ${network.size}
        depth: ${network.depth}
        layer_norm: ${network.layer_norm}
        activation: ${network.activation}
        dropout: ${network.dropout}
core:
    node:
        size: ${network.size}
        depth: ${network.depth}
        layer_norm: ${network.layer_norm}
        activation: ${network.activation}
        dropout: ${network.dropout}
    edge:
        size: ${network.size}
        depth: ${network.depth}
        layer_norm: ${network.layer_norm}
        activation: ${network.activation}
        dropout: ${network.dropout}
    glob:
        size: ${network.size}
        depth: ${network.depth}
        layer_norm: ${network.layer_norm}
        activation: ${network.activation}
        dropout: ${network.dropout}
out:
    node:
        size: 1
        depth: 1
        layer_norm: true
        activation: Identity
        dropout: 0.0
    edge:
        size: 1
        depth: 1
        layer_norm: true
        activation: Identity
        dropout: 0.0
    glob:
        size: 1
        depth: 1
        layer_norm: true
        activation: Identity
        dropout: 0.0

# defaults
dropout: 0.2
activation: LeakyReLU
size: 32
depth: 3
layer_norm: true
aggregator_activation: LeakyReLU
pass_global_to_edge: true
pass_global_to_node: true
connectivity:
    x0_to_edge: false
    x1_to_edge: false
    g_to_edge: false
    g_to_node: false
    edge_to_node: false
    edge_to_glob: false
    node_to_glob: false
edge_block_to_node_aggregators:
    - add
global_block_to_node_aggregators:
    - add
global_block_to_edge_aggregators:
    - add