# @package _group_
encode:
    node:
        size: 16
        depth: 1
        layer_norm: true
        activation: ${network.activation}
        dropout: ${network.dropout}
    edge:
        size: 16
        depth: 1
        layer_norm: true
        activation: ${network.activation}
        dropout: ${network.dropout}
    glob:
        size: 16
        depth: 1
        layer_norm: true
        activation: ${network.activation}
        dropout: ${network.dropout}
core:
    node:
        size: 32
        depth: 3
        layer_norm: true
        activation: ${network.activation}
        dropout: ${network.dropout}
    edge:
        size: 32
        depth: 3
        layer_norm: true
        activation: ${network.activation}
        dropout: ${network.dropout}
    glob:
        size: 32
        depth: 3
        layer_norm: true
        activation: ${network.activation}
        dropout: ${network.dropout}
out:
    node:
        size: 2
        depth: 1
        layer_norm: true
        activation: Identity
        dropout: 0.0
    edge:
        size: 2
        depth: 1
        layer_norm: true
        activation: Identity
        dropout: 0.0
    glob:
        size: 1
        depth: 1
        layer_norm: true
        activation: Identity
        dropout: 0.0

# defaults
dropout: 0.2
activation: LeakyReLU
layer_norm: true
aggregator_activation: LeakyReLU
pass_global_to_edge: true
pass_global_to_node: true
edge_block_to_node_aggregators:
    - add
global_block_to_node_aggregators:
    - add
global_block_to_edge_aggregators:
    - add