name: Documentation

on:
  push:
    branches: [ master ]

env:
  CACHE_IMAGE: jvrana/docker-ci-cache
  DOCKER_BUILDKIT: 1


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        path: master
        ref: master
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: ghpages
        ref: gh-pages
#    - name: Log in to docker hub
#      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
#    - name: Build the Docker image
#      run: |
#        cd master
#        DOCKER_BUILDKIT=1 docker build . \
#        . \
#        -f docker/docs/Dockerfile \
#        -t actions/caldera:docs
#    - name: Build the Documentation
#      run: ./docker/docs/build.sh actions/caldera:docs gh-pages
    - name: Do stuff in master
      run: |
        cd master
        ls
        cd ..
    - name: Commit to gh-pages
      run: |
        cd ghpages
        ls
        cd ..
