name: Documentation

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -f docker/docs/Dockerfile -t actions/caldera:docs
    - name: Build the Documentation
      run: ./docker/docs/build.sh actions/caldera:docs gh-pages
    - uses: actions/upload-artifact@v2
      with:
        name: html
        path: gh-pages/html
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: commit
      run: |
        git add .
        echo $(git status)
