# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: idk
        uses: actions/checkout@v2
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            USERNAME:  ${{ secrets.USERNAME }}
            PASSWORD:  ${{ secrets.PASSWORD }}
      - run: |
          git clone --no-checkout https://$USERNAME:$GITHUB_TOKEN@github.com/jvrana/caldera.git --branch gh-pages --single-branch gh-pages-git
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf gh-pages-git/*
          cp -r docs/build/html/* gh-pages-git
          cd gh-pages-git
          git add .
          git commit -m "generated"
          git push

