# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: idk
        uses: actions/checkout@v2
        
      - shell: bash
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            USERNAME:  ${{ secrets.USERNAME }}
      - run: |
          echo $USERNAME
          echo $GITHUB_TOKEN
          git clone https://$USERNAME:b4174934b5c9d8cffc47560fe7ac09d140f3b014@github.com/jvrana/caldera.git gh-pages-git
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf gh-pages-git/*
          cp -r docs/build/html/* gh-pages-git
          cd gh-pages-git
          git add .
          git commit -m "generated"
          git push

